### ISSUE TITLE
Failed to register - 504 error (initial app setup)

### ISSUE THREAD

**Issue by fijiaaron** [dlwhitehurst/virtualyou#1]
When I attempt to register, I get a 504 error message:

**vy-userauth logs** 

```
[HPM] Error occurred while proxying request localhost:3000/api/vy/all to http://localhost:8080/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while proxying request localhost:3000/api/auth/signup to http://localhost:8080/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors
```

_**I've probably missed a step to setup**_

Here is what I do:

1. set environment variables (DB_HOST, etc)
  source .env 

2.  Create database and grant privileges
  create database virtualyou;
  grant all privileges on virtualyou.* to vyuser@localhost identified by "vypassword";
   
3. Run userauth service
  npm install && npm start -- mode=init

4. Insert roles
 mysql -h $DB_HOST -D $DB_SCHEMA -u $DB_USERNAME -p < inserts.sql

5. Start app  
  npm install && npm start

```
MariaDB [virtualyou]> show tables;
+----------------------+
| Tables_in_virtualyou |
+----------------------+
| roles                |
| user_roles           |
| users                |
+----------------------+
3 rows in set (0.003 sec)

MariaDB [virtualyou]> select * from roles;
+----+---------+---------------------+---------------------+
| id | name    | createdAt           | updatedAt           |
+----+---------+---------------------+---------------------+
|  1 | owner   | 2023-11-02 15:00:34 | 2023-11-02 15:00:34 |
|  2 | agent   | 2023-11-02 15:00:34 | 2023-11-02 15:00:34 |
|  3 | monitor | 2023-11-02 15:00:34 | 2023-11-02 15:00:34 |
|  4 | admin   | 2023-11-02 15:00:34 | 2023-11-02 15:00:34 |
+----+---------+---------------------+---------------------+
4 rows in set (0.002 sec)
```

**.env**

```
export COOKIE_SECRET=virtual-you-secret
export DB_HOST='localhost'
export DB_USERNAME='vyuser'
export DB_PASSWORD='vypassword'
export DB_SCHEMA='virtualyou'
export NODE_OPTIONS="--unhandled-rejections=strict"
```

**Comment by fijiaaron** [comment]
I have not tried the docker containers

**Comment by dlwhitehurst** [comment]
I'm going to create two branches. First, I'll `git branch development` and then `git branch feature/app-1` and fix this with 1) code and 2) better README instructions.

**Comment by dlwhitehurst** [comment]
This is now fixed by PR https://github.com/dlwhitehurst/virtualyou/pull/2

Please test using `development` branch. I'm going to create new issues and feature/... branches for each. I'll do PRs and also leave feature branches for awhile as we proceed.
